name: Build & Test

on:
  push:
    branches: ["**"]  # Run on push to any branch
  pull_request:
    branches: ["**"]  # Run on PRs to any branch

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and Run Unit Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Set up compiler (Clang)
        run: sudo apt-get install -y clang

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
      

      - name: Create build directory
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=17

      - name: Build project
        run: cmake --build build

      - name: Run clang-tidy
        run: clang-tidy $(find src/ -name '*.cpp') -- -Iinclude -std=c++17
      
      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure
