name: Build & Test

on:
  push:
    branches: ["**"]  # Run on push to any branch
  pull_request:
    branches: ["**"]  # Run on PRs to any branch

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and Run Unit Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang clang-tidy lcov llvm

      - name: Make scripts executable
        run: chmod +x scripts/*.sh
      
      - name: Build with coverage
        run: ./scripts/build_with_coverage.sh

      - name: Run coverage analysis
        run: ./scripts/run_coverage.sh

      - name: Run clang-tidy
        run: clang-tidy $(find src/ -name '*.cpp') -- -Iinclude -std=c++17
      
      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/tests/coverage.txt